#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

#export PATH="$PATH:$HOME/usr/bin/python3"
export PATH="$PATH:$HOME/.local/script"
export PATH="$PATH:$HOME/.local/script/status-bar"
export PATH="$PATH:$HOME/.local/script/personal"
export PATH="$PATH:$HOME/.emacs.d/bin"
export VISUAL=nvim
export EDITOR=nvim

export XDG_CONFIG_HOME="$HOME/.config"
export QT_GRAPHICSSYSTEM=native
export PASSWORD_STORE_DIR="$HOME/.local/pass/password-store"
export DESKTOP_SESSION=plasma

export BIB="$HOME/doc/bib/bib.bib"


# This is the list for lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=:\
*.webp=:\
*.ico=:\
*.jpg=:\
*.jpe=:\
*.jpeg=:\
*.gif=:\
*.svg=:\
*.tif=:\
*.tiff=:\
*.xcf=🖌:\
*.html=:\
*.xml=:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=:\
*.djvu=:\
*.epub=:\
*.csv=📓:\
*.xlsx=📓:\
*.styl=π:\
*.cls=π:\
*.tex=π:\
*.md=:\
*.r=:\
*.R=:\
*.rmd=:\
*.Rmd=:\
*.m=:\
*.mp3=ﱘ:\
*.opus=ﱘ:\
*.ogg=ﱘ:\
*.m4a=ﱘ:\
*.flac=:\
*.wav=:\
*.mkv=:\
*.mp4=:\
*.webm=:\
*.mpeg=:\
*.avi=:\
*.mov=:\
*.mpg=:\
*.wmv=:\
*.m4b=:\
*.flv=:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
"

